Update from the upstream
Allow non-root users to customize and use KeyTalk Linux client

diff --git a/Software/Client/Projects/makefile b/Software/Client/Projects/makefile
--- a/Software/Client/Projects/makefile
+++ b/Software/Client/Projects/makefile
@@ -13,7 +13,7 @@ check_devenv:
 		exit 1; \
 	fi; \
 	if [[ ! -f /etc/debian_version && ! -f /etc/centos-release && ! -f /etc/redhat-release ]]; then \
-		echo "Linux Debian/RedHat/CentOS platform required to build KeyTalk Linux client" 1>&2 ; \
+		echo "Linux Debian/Ubuntu/RedHat/CentOS platform required to build KeyTalk Linux client" 1>&2 ; \
 		exit 1; \
 	fi;
 
