Adding Support for RHEL/CentOS 6&7

diff --git a/Software/Client/Projects/makefile b/Software/Client/Projects/makefile
--- a/Software/Client/Projects/makefile
+++ b/Software/Client/Projects/makefile
@@ -1,3 +1,7 @@
+#################################################
+# RHEL/CentOS 6 & 7 support added on 8 May 2018 #
+#################################################
+
 PRJS=ReseptConsoleClient ReseptConfigManager ReseptConfigTool ReseptPrGenerator ReseptHwsigDump ReseptPythonClient ReseptInstaller/ConfigUpdater ReseptInstaller/linux/bin ReseptInstaller/linux/apache_remote_deployment
 MAKE_FLAGS=-s
 
@@ -12,14 +16,17 @@ check_devenv:
 		echo "Linux platform required to build KeyTalk Linux client" 1>&2 ; \
 		exit 1; \
 	fi; \
-	if [ ! -f /etc/debian_version ]; then \
-		echo "Linux Debian platform required to build KeyTalk Linux client" 1>&2 ; \
+	if [[ ! -f /etc/debian_version && ! -f /etc/centos-release && ! -f /etc/redhat-release ]]; then \
+		echo "Linux Debian/RedHat/CentOS platform required to build KeyTalk Linux client" 1>&2 ; \
 		exit 1; \
 	fi; \
-	if dpkg -s libcurl-dev > /dev/null 2>&1; then \
-		echo "Curl developent package should NOT be installed to avoid possible build conflicts with local curl libs" 1>&2; \
-		exit 1; \
-	fi
+	if [ -f /etc/debian_version ]; then \
+		if dpkg -s libcurl-dev > /dev/null 2>&1 ; then \
+			echo "Curl developent package should NOT be installed to avoid possible build conflicts with local curl libs" 1>&2; \
+			exit 1; \
+		fi; \
+	fi; 
+	
 
 release debug: check_devenv
 	@set -e;			\
@@ -41,4 +48,4 @@ install: check_devenv
 	for dir in $(PRJS); do \
 		echo "--- Installing $$dir";	\
 		make -C $$dir $(MAKE_FLAGS) install;		\
-	done;
+done;
